apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::127982810038:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HZ6J6R2KE6Z2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::127982810038:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-23T11:45:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1513"
  uid: b508bf1b-a3f4-4939-a7e5-5759a91c2b34
